services:
  n8n:
    build: ./docker/n8n
    container_name: gmail-automate-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
      - ./scripts:/scripts
      - ./credentials:/credentials
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network: