#* Get n8n docker file from official repo v.1.113.2
FROM n8nio/n8n:1.113.2

#* Switch to root user to install depedencies and build
USER root

#* Install depedencies
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     python3 \
#     python3-pip \
#     python3-dev \
#     && rm -rf /var/lib/apt/lists/*

RUN apk add --no-cache \
    python3 \
    py3-pip \
    python3-dev

#* Installl pip packages
# RUN pip3 install --no-cache-dir --upgrade pip

#* Install Python libraries for excel and pydrive2
RUN python3 -m venv /venv \
    && . /venv/bin/activate \
    && pip3 install --no-cache-dir --upgrade pip \
    openpyxl \
    pandas \
    pydrive2 \
    python-dotenv \
    # add google api libraries
    google-auth \
    google-auth-oauthlib \
    google-auth-httplib2 \
    google-api-python-client

ENV PATH="/venv/bin:$PATH"

# RUN pip3 install --no-cache-dir --upgrade pip \
#     openpyxl \
#     pandas \
#     pydrive2 \
#     python-dotenv

#* Set Workdir for excel-merge script
WORKDIR /scripts

RUN mkdir -p /scripts && chown -R node:node /scripts

#* Switch back to n8n user
USER node